### ISSUE TITLE
Pi instructions

### ISSUE THREAD

**Issue by bennuttall** [amos1969/pandas-for-teachers#1]
This is how I got it working:

```
sudo apt install libatlas3-base
sudo pip3 install numpy jupyter pandas matplotlib holoviews[all] plotly --ignore-installed
sudo pip3 install "bokeh<0.13dev"
```

There's no need to recompile numpy, but the one from piwheels has a dependency on atlas.

The `--ignore-installed` option is a handy way of leaving the system (apt) numpy (etc) alone but still installing a newer version.

**Comment by amos1969** [comment]
Thanks Ben, added them to the instructions in the first sheet.
